#!/usr/bin/env python
"""Turn the raw result CSVs into the markdown tables used by docs/04_results.md.

Writes results/tables.md.
"""

from __future__ import annotations

import os.path as osp
import sys

import numpy as np
import pandas as pd

sys.path.insert(0, osp.abspath(osp.join(osp.dirname(__file__), "..")))

from phash_defense import attacks as A  # noqa: E402
from phash_defense import hashes as H  # noqa: E402

RESULTS = osp.abspath(osp.join(osp.dirname(__file__), "..", "results"))
OUT = osp.join(RESULTS, "tables.md")

#: primary metric: AUC inside the attacked class, best of the two directions
KEY = "auc_target_class_best"


def md(df, floatfmt="{:.3f}"):
    df = df.copy()
    for c in df.columns:
        if df[c].dtype.kind == "f":
            df[c] = df[c].map(lambda v: "" if not np.isfinite(v) else floatfmt.format(v))
    return df.to_markdown()


def attack_table():
    from phash_defense.data import cifar10

    clean, _ = cifar10(train=True)
    rows = []
    for name, spec in A.ATTACKS.items():
        try:
            ps = A.build(name, 0.05, 0, 0)
        except Exception:  # noqa: BLE001
            continue
        m = ps.poison_mask
        d = ps.images[m].astype(int) - clean[m].astype(int)
        rows.append(dict(attack=name, source=spec.source, trigger=spec.trigger_type,
                         visibility=spec.visibility, label=spec.label,
                         Linf=int(np.abs(d).max()), L1_per_px=float(np.abs(d).mean()),
                         pixels_changed_pct=float(100 * (np.abs(d) > 0).mean())))
    return pd.DataFrame(rows).set_index("attack")


def control_adjusted(df, control):
    """AUC above the label-flip control: the *trigger-specific* detection power.

    A dirty-label attack moves images of other classes into the target class, so
    a detector scores above chance even with no trigger at all. The control run
    (`label_flip_only`) measures that baseline for every (hash, detector) pair.
    """
    base = control.set_index(["hash", "detector"])[KEY]
    d = df.copy()
    d["delta"] = [r[KEY] - base.get((r["hash"], r["detector"]), 0.5)
                  for _, r in d.iterrows()]
    return d, base


def sections(df, rates=None, e2e=None, cost=None, control=None):
    out = []
    out.append("# Result tables\n")
    out.append("Generated by `scripts/make_tables.py` from `results/*.csv`.\n")

    out.append("\n## T1. Attack catalogue (poison rate 5 %, target class 0)\n")
    out.append(md(attack_table()))

    piv = df.pivot_table(index="hash", columns="attack", values=KEY, aggfunc="max")
    piv["mean"] = piv.mean(axis=1)
    piv = piv.sort_values("mean", ascending=False)
    out.append("\n\n## T2. Detection AUC inside the attacked class, best detector per cell\n")
    out.append(md(piv))

    dpiv = df.pivot_table(index="detector", columns="attack", values=KEY, aggfunc="max")
    dpiv["mean"] = dpiv.mean(axis=1)
    dpiv = dpiv.sort_values("mean", ascending=False)
    out.append("\n\n## T3. Same, by detection statistic\n")
    out.append(md(dpiv))

    best = (df.sort_values(KEY, ascending=False)
              .groupby("attack")
              .head(1)[["attack", "hash", "detector", "direction", KEY,
                        "tpr@1fpr_target_class_best", "auc", "elimination_rate",
                        "sacrifice_rate"]]
              .set_index("attack").sort_values(KEY, ascending=False))
    out.append("\n\n## T4. Best configuration per attack\n")
    out.append(md(best))

    if control is not None and len(control):
        d, base = control_adjusted(df, control)
        cp = base.sort_values(ascending=False).reset_index()
        out.append("\n\n## T4b. Control: labels flipped with **no trigger at all**\n")
        out.append("Any AUC above 0.5 here is pure label-noise detection, not trigger "
                   f"detection. Mean over all (hash, detector) pairs: {base.mean():.3f}, "
                   f"maximum {base.max():.3f}.\n")
        out.append(md(cp.head(12).set_index(["hash", "detector"])))
        dp = d.pivot_table(index="hash", columns="attack", values="delta", aggfunc="max")
        dp["mean"] = dp.mean(axis=1)
        dp = dp.sort_values("mean", ascending=False)
        out.append("\n\n## T4c. Trigger-specific detection power (AUC above the control)\n")
        out.append(md(dp))

    fam = df.groupby(["family", "threshold"])[KEY].mean().reset_index()
    out.append("\n\n## T5. Mean AUC by hash family and threshold type\n")
    out.append(md(fam.set_index(["family", "threshold"])))

    g = df.groupby(["hash", "n_bits"])[KEY].mean().reset_index()
    g = g.sort_values(KEY, ascending=False)
    out.append("\n\n## T6. Detection power vs hash length\n")
    out.append(md(g.set_index("hash")))

    if cost is not None:
        c = cost[(cost["protocol"].str.startswith("3PC")) & (cost["network"] == "LAN")]
        c = c.set_index("hash")["online_bits"] / 8 / 1000  # kB per image
        j = g.set_index("hash").join(c.rename("mpc_kB_per_image"), how="inner")
        j = j.sort_values(KEY, ascending=False)
        out.append("\n\n## T7. Detection power vs MPC cost (Pareto)\n")
        out.append(md(j))

    if rates is not None and len(rates):
        rp = rates.pivot_table(index="rate", columns="attack", values=KEY, aggfunc="max")
        out.append("\n\n## T8. Best AUC vs poison rate\n")
        out.append(md(rp))

    if e2e is not None and len(e2e):
        cols = [c for c in ["attack", "setting", "ba", "asr", "elimination_rate",
                            "sacrifice_rate", "detection_auc", "train_size", "epochs"]
                if c in e2e.columns]
        out.append("\n\n## T9. End-to-end: benign accuracy and attack success rate\n")
        out.append(md(e2e[cols].set_index(["attack", "setting"]), "{:.4f}"))

    return "\n".join(out)


def main():
    df = pd.read_csv(osp.join(RESULTS, "detection.csv"))
    df = df[np.isfinite(df[KEY])]
    rates = None
    p = osp.join(RESULTS, "detection_rates.csv")
    if osp.exists(p):
        rates = pd.read_csv(p)
        rates = rates[np.isfinite(rates[KEY])]
    e2e = None
    p = osp.join(RESULTS, "end2end.csv")
    if osp.exists(p):
        e2e = pd.read_csv(p)
    cost = None
    p = osp.join(RESULTS, "mpc_hash_cost.csv")
    if osp.exists(p):
        cost = pd.read_csv(p)
    control = None
    p = osp.join(RESULTS, "detection_control.csv")
    if osp.exists(p):
        control = pd.read_csv(p)
        control = control[np.isfinite(control[KEY])]

    text = sections(df, rates, e2e, cost, control)
    with open(OUT, "w") as f:
        f.write(text + "\n")
    print(text)
    print(f"\nwrote {OUT}")


if __name__ == "__main__":
    main()
